language: cpp
branches:
  only:
  - master
matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON=3.6
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - libblas-dev
    - liblapack-dev
    - gfortran
    - cmake
    - python3-dev
    - libboost-all-dev
    - libgsl0-dev
    - libeigen3-dev

before_install:
- |
  pyenv shell 3.6.3
- |
  PIP=pip
  PY=python$PYTHON
  which $PY
  which pip
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    export CXX=g++-4.9 CC=gcc-4.9; 
    pip install --user --upgrade pip virtualenv    
  fi

- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    virtualenv -p $PY venv
    source venv/bin/activate
  fi

install:
- cmake similarity_search -DWITH_EXTRAS=1
- make -j 6
- travis_wait travis_retry $PIP install -r python_bindings/requirements.txt scipy six flake8 wheel
- cd python_bindings && $PY setup.py build install && $PY -W ignore setup.py bdist_wheel && ls -hlR dist/* && cd ..

script:
- true

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  skip_cleanup: true
  overwrite: true
  file_glob: false
  file: python_bindings/dist/nmslib-1.7.3.4-cp36-cp36m-linux_x86_64.whl
  on:
    repo: timedcy/nmslib
    all_branches: true
    tags: false
    
cache:
  - apt
  - directories:
    - $HOME/.cache/pip

